#!/usr/bin/env python3
"""
Pangea Scaffold — Generate a new atlas data.js from config.
================================================================
Replaces Phase 1A-1F with a single command.

Usage:
  python3 pangea_scaffold.py ATLAS_KEY

  Reads atlas config from pangea_state.json and generates ATLAS_KEY/data.js
  with empty data arrays ready for item writing.

  Or with explicit config:
  python3 pangea_scaffold.py ATLAS_KEY --name "Clima" --subtitle "The Climate Atlas" \
    --icon "🌡" --year-min -8000 --year-max 2024 \
    --thread-label "Climate Chains" --heritage-label "Climate Heritage" \
    --arc-label "Climate Arc" --count-label "events active" \
    --hint "TAP AN EVENT  ·  PINCH TO ZOOM  ·  DRAG TO PAN" \
    --fp-labels "Severity,Duration,Range,Frequency,Impact,Recovery" \
    --fp-keys "sev,dur,rng,frq,imp,rec"
"""

import argparse
import json
import sys
from pathlib import Path


def scaffold(args):
    atlas = args.atlas
    out_dir = Path(atlas)
    out_dir.mkdir(exist_ok=True)

    # Try to get config from state file
    state_path = Path("pangea_state.json")
    state_info = {}
    if state_path.exists():
        state = json.loads(state_path.read_text())
        state_info = state.get("atlases", {}).get(atlas, {})

    # Resolve config with CLI overrides > state file > defaults
    name = args.name or state_info.get("homepage_name", atlas.capitalize())
    subtitle = args.subtitle or f"The {name} Atlas"
    icon = args.icon or "🌍"
    year_min = args.year_min or -8000
    year_max = args.year_max or 2024
    thread_label = args.thread_label or f"{name} Chains"
    heritage_label = args.heritage_label or f"{name} Heritage"
    arc_label = args.arc_label or f"{name} Arc"
    count_label = args.count_label or "items active"
    hint = args.hint or "TAP AN ITEM  ·  PINCH TO ZOOM  ·  DRAG TO PAN"
    skip_label = args.skip_label or f"Skip to {name.lower()} panel"
    map_aria = args.map_aria or f"World map with {name.lower()} markers"
    info_aria = args.info_aria or f"{name} details"
    cluster_label = args.cluster_label or f"Select {name.lower()} item"

    # FP
    fp_labels_str = args.fp_labels or "Axis1,Axis2,Axis3,Axis4,Axis5,Axis6"
    fp_keys_str = args.fp_keys or "ax1,ax2,ax3,ax4,ax5,ax6"
    fp_labels = [x.strip() for x in fp_labels_str.split(",")]
    fp_keys = [x.strip() for x in fp_keys_str.split(",")]

    # Meta
    meta_desc = args.meta_description or f"Explore 100 {name.lower()} items across history on an interactive world map. Navigate a continuous timeline with 20 interpretive lenses, chains, What-If scenarios, and a Herstory mode."
    og_desc = args.og_description or f"100 {name.lower()} items. Mapped, connected, and explorable."

    # Timeline labels (7 evenly spaced)
    span = year_max - year_min
    tl_steps = [year_min + int(span * i / 6) for i in range(7)]
    tl_labels = []
    for y in tl_steps:
        if y < 0:
            tl_labels.append(f"{abs(y)} BCE")
        elif y == 0:
            tl_labels.append("1 CE")
        else:
            tl_labels.append(f"{y} CE")

    # Build the slider functions
    slider_fn = f"""function sliderToYear(v){{
  v=parseInt(v);
  return Math.round({year_min}+(v/1000)*({year_max}-({year_min})));
}}
function yearToSlider(yr){{
  yr=parseInt(yr);
  return Math.round(((yr-({year_min}))/({year_max}-({year_min})))*1000);
}}"""

    # Assemble data.js
    data_js = f"""// {name} — {subtitle}
// Atlas data file for the Pangea build system.
// Generated by pangea_scaffold.py. Fill in data arrays below.

const ATLAS_CONFIG = {{
  name: '{name}',
  subtitle: '{subtitle}',
  icon: '{icon}',
  year_min: {year_min},
  year_max: {year_max},
  meta_description: '{meta_desc}',
  meta_keywords: '{name.lower()}, history, interactive, atlas',
  og_description: '{og_desc}',
  thread_label: '{thread_label}',
  heritage_label: '{heritage_label}',
  arc_label: '{arc_label}',
  count_label: '{count_label}',
  hint_text: '{hint}',
  skip_label: '{skip_label}',
  map_aria: '{map_aria}',
  info_aria: '{info_aria}',
  cluster_label: '{cluster_label}',
}};

// ── Timeline labels ──
const TL_LABELS = [{','.join(f"'{l}'" for l in tl_labels)}];

// ── Slider functions ──
{slider_fn}

// ── Year init ──
let year = {year_min};

// ══════════════════════════════════════════════════════════════
// LENSES — minimum 20, sorted alphabetically by lbl
// ══════════════════════════════════════════════════════════════
const LENSES = [
  // {{id:'lens_id', ico:'⊕', lbl:'Label Text', col:'#hex'}},
];

// ══════════════════════════════════════════════════════════════
// ERAS — timeline era names shown in header
// ══════════════════════════════════════════════════════════════
const ERAS = [
  // {{y: -8000, n: 'ERA NAME'}},
];

// ══════════════════════════════════════════════════════════════
// ITEMS — minimum 100, ordered by s (start year) ascending
// ══════════════════════════════════════════════════════════════
const ITEMS = [
];

// ══════════════════════════════════════════════════════════════
// TRANSMISSIONS — minimum 15 chains
// ══════════════════════════════════════════════════════════════
const TRANSMISSIONS = [
];

// ══════════════════════════════════════════════════════════════
// WOMEN — Herstory data, mandatory
// ══════════════════════════════════════════════════════════════
const WOMEN = {{
}};

// ══════════════════════════════════════════════════════════════
// FINGERPRINT AXES — 6 axes, values 0-10
// ══════════════════════════════════════════════════════════════
const FP_LABELS = [{','.join(f"'{l}'" for l in fp_labels)}];
const FP_KEYS = [{','.join(f"'{k}'" for k in fp_keys)}];

// ══════════════════════════════════════════════════════════════
// HERITAGE REGIONS
// ══════════════════════════════════════════════════════════════
const HERITAGE_REGIONS = {{
}};

const HERITAGE_REASONS = {{
}};
"""

    out_path = out_dir / "data.js"
    out_path.write_text(data_js, encoding="utf-8")
    print(f"Scaffolded {atlas}/data.js")
    print(f"  Name: {name} — {subtitle}")
    print(f"  Timeline: {year_min} to {year_max}")
    print(f"  FP axes: {fp_labels}")
    print(f"  Next: fill in LENSES, ERAS, then write items in ITEMS array")
    print(f"  Build: python3 build.py {atlas}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scaffold a new Pangea atlas")
    parser.add_argument("atlas", help="Atlas directory name (lowercase)")
    parser.add_argument("--name", help="Display name")
    parser.add_argument("--subtitle", help="Subtitle (e.g. 'The Climate Atlas')")
    parser.add_argument("--icon", help="Favicon emoji")
    parser.add_argument("--year-min", type=int, help="Timeline start year")
    parser.add_argument("--year-max", type=int, help="Timeline end year")
    parser.add_argument("--thread-label", help="Threads mode label")
    parser.add_argument("--heritage-label", help="Heritage mode label")
    parser.add_argument("--arc-label", help="Arc label in drawer")
    parser.add_argument("--count-label", help="Item count label")
    parser.add_argument("--hint", help="Map hint text")
    parser.add_argument("--skip-label", help="Skip link text")
    parser.add_argument("--map-aria", help="Map SVG aria-label")
    parser.add_argument("--info-aria", help="Info panel aria-label")
    parser.add_argument("--cluster-label", help="Cluster picker label")
    parser.add_argument("--fp-labels", help="Comma-separated FP axis labels")
    parser.add_argument("--fp-keys", help="Comma-separated FP axis keys")
    parser.add_argument("--meta-description", help="Meta description text")
    parser.add_argument("--og-description", help="OG description text")
    args = parser.parse_args()
    scaffold(args)
