// Clima — The Climate Atlas
// Atlas data file for the Pangea build system.
// Generated by pangea_scaffold.py. Fill in data arrays below.

const ATLAS_CONFIG = {
  name: 'Clima',
  subtitle: 'The Climate Atlas',
  icon: '🌡',
  year_min: -8000,
  year_max: 2024,
  meta_description: 'Explore 100 clima items across history on an interactive world map. Navigate a continuous timeline with 20 interpretive lenses, chains, What-If scenarios, and a Herstory mode.',
  meta_keywords: 'clima, history, interactive, atlas',
  og_description: '100 clima items. Mapped, connected, and explorable.',
  thread_label: 'Climate Chains',
  heritage_label: 'Climate Heritage',
  arc_label: 'Climate Arc',
  count_label: 'events active',
  hint_text: 'TAP AN EVENT  ·  PINCH TO ZOOM  ·  DRAG TO PAN',
  skip_label: 'Skip to clima panel',
  map_aria: 'World map with clima markers',
  info_aria: 'Clima details',
  cluster_label: 'Select clima item',
};

// ── Timeline labels ──
const TL_LABELS = ['8000 BCE','6330 BCE','4659 BCE','2988 BCE','1318 BCE','353 CE','2024 CE'];

// ── Slider functions ──
function sliderToYear(v){
  v=parseInt(v);
  return Math.round(-8000+(v/1000)*(2024-(-8000)));
}
function yearToSlider(yr){
  yr=parseInt(yr);
  return Math.round(((yr-(-8000))/(2024-(-8000)))*1000);
}

// ── Year init ──
let year = -8000;

// ══════════════════════════════════════════════════════════════
// LENSES — minimum 20, sorted alphabetically by lbl
// ══════════════════════════════════════════════════════════════
const LENSES = [
  // {id:'lens_id', ico:'⊕', lbl:'Label Text', col:'#hex'},
];

// ══════════════════════════════════════════════════════════════
// ERAS — timeline era names shown in header
// ══════════════════════════════════════════════════════════════
const ERAS = [
  // {y: -8000, n: 'ERA NAME'},
];

// ══════════════════════════════════════════════════════════════
// ITEMS — minimum 100, ordered by s (start year) ascending
// ══════════════════════════════════════════════════════════════
const ITEMS = [
];

// ══════════════════════════════════════════════════════════════
// TRANSMISSIONS — minimum 15 chains
// ══════════════════════════════════════════════════════════════
const TRANSMISSIONS = [
];

// ══════════════════════════════════════════════════════════════
// WOMEN — Herstory data, mandatory
// ══════════════════════════════════════════════════════════════
const WOMEN = {
};

// ══════════════════════════════════════════════════════════════
// FINGERPRINT AXES — 6 axes, values 0-10
// ══════════════════════════════════════════════════════════════
const FP_LABELS = ['Severity','Duration','Range','Frequency','Impact','Recovery'];
const FP_KEYS = ['sev','dur','rng','frq','imp','rec'];

// ══════════════════════════════════════════════════════════════
// HERITAGE REGIONS
// ══════════════════════════════════════════════════════════════
const HERITAGE_REGIONS = {
};

const HERITAGE_REASONS = {
};
