// Aqua — The Aqua Atlas
// Atlas data file for the Pangea build system.
// Generated by pangea_scaffold.py. Fill in data arrays below.

const ATLAS_CONFIG = {
  name: 'Aqua',
  subtitle: 'The Water Atlas',
  icon: '💧',
  year_min: -8000,
  year_max: 2024,
  meta_description: 'Explore 100 water events across history on an interactive world map. Navigate a continuous timeline with 20 interpretive lenses, hydro chains, What-If scenarios, and a Herstory mode.',
  meta_keywords: 'water, rivers, drought, flood, irrigation, civilisation, history, interactive, atlas',
  og_description: '100 water events. Every civilisation that water built. Every one it ended.',
  thread_label: 'Hydro Chains',
  heritage_label: 'Water Heritage',
  arc_label: 'Water Arc',
  count_label: 'events active',
  hint_text: 'TAP AN EVENT  ·  PINCH TO ZOOM  ·  DRAG TO PAN',
  skip_label: 'Skip to water panel',
  map_aria: 'World map with water event markers',
  info_aria: 'Water event details',
  cluster_label: 'Select water event',
};

// ── Timeline labels ──
const TL_LABELS = ['8000 BCE','6330 BCE','4659 BCE','2988 BCE','1318 BCE','353 CE','2024 CE'];

// ── Slider functions ──
function sliderToYear(v){
  v=parseInt(v);
  return Math.round(-8000+(v/1000)*(2024-(-8000)));
}
function yearToSlider(yr){
  yr=parseInt(yr);
  return Math.round(((yr-(-8000))/(2024-(-8000)))*1000);
}

// ── Year init ──
let year = -8000;

// ══════════════════════════════════════════════════════════════
// LENSES — minimum 20, sorted alphabetically by lbl
// ══════════════════════════════════════════════════════════════
const LENSES = [
  // {id:'lens_id', ico:'⊕', lbl:'Label Text', col:'#hex'},
];

// ══════════════════════════════════════════════════════════════
// ERAS — timeline era names shown in header
// ══════════════════════════════════════════════════════════════
const ERAS = [
  // {y: -8000, n: 'ERA NAME'},
];

// ══════════════════════════════════════════════════════════════
// ITEMS — minimum 100, ordered by s (start year) ascending
// ══════════════════════════════════════════════════════════════
const ITEMS = [
];

// ══════════════════════════════════════════════════════════════
// TRANSMISSIONS — minimum 15 chains
// ══════════════════════════════════════════════════════════════
const TRANSMISSIONS = [
];

// ══════════════════════════════════════════════════════════════
// WOMEN — Herstory data, mandatory
// ══════════════════════════════════════════════════════════════
const WOMEN = {
};

// ══════════════════════════════════════════════════════════════
// FINGERPRINT AXES — 6 axes, values 0-10
// ══════════════════════════════════════════════════════════════
const FP_LABELS = ['Scale','Duration','Conflict','Innovation','Impact','Legacy'];
const FP_KEYS = ['scl','dur','con','inn','imp','leg'];

// ══════════════════════════════════════════════════════════════
// HERITAGE REGIONS
// ══════════════════════════════════════════════════════════════
const HERITAGE_REGIONS = {
};

const HERITAGE_REASONS = {
};
